### ISSUE TITLE
stopped working rant

### ISSUE THREAD

**Issue by fartwhif** [tadwohlrapp/amazon-show-seller-info-userscript#3]
i know you explicitly state that we have no right to know who the seller is in the US, but it has been working for years, and recently within the past few weeks, it stopped working.  Bezos wills it i guess...

**Comment by tadwohlrapp** [comment]
Hey @fartwhif, you're right, it should work on amazon.com, too!

When I first wrote the script, amazon.com did not provide detailed seller info, but now it seems like they do.

Guess I'll update the script in the coming weeks then. Thanks for letting me know!
